name: "Warema WMS bridge"
description: "MQTT interface to Warema WMS"
url: "https://github.com/giannello/addon-warema-bridge"
version: "dev"
slug: "warema_wms_bridge"
startup: "services"
init: false
arch:
  - aarch64
  - amd64
uart: true
services:
  - mqtt:need
